### ISSUE TITLE
Not updated

### ISSUE THREAD

**Issue by Thomas-6freedom** [MicrosoftDocs/msix-docs.fr-fr#1]
The HoloLens 2 is ARM64 so the page is not updated

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 3d3ebc79-107e-4da3-a69e-2833e4b4891f
* Version Independent ID: bcb79b16-6786-3330-d3d6-052b8391a442
* Content: [Architectures de package d’application - MSIX](https://docs.microsoft.com/fr-fr/windows/msix/package/device-architecture#feedback)
* Content Source: [msix-src/package/device-architecture.md](https://github.com/MicrosoftDocs/msix-docs.fr-fr/blob/live/msix-src/package/device-architecture.md)
* Product: **msix**
* GitHub Login: @olprod

**Comment by srvbpigh** [comment]
Hello, @Thomas-6freedom
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Bonjour @Thomas-6freedom,  

Merci pour votre contribution. Votre feedback porte sur la documentation en langue anglaise.  

Nous l’avons donc transféré au dépôt Anglais. Vous pouvez consulter le statut de votre demande ici : https://github.com/MicrosoftDocs/msix-docs/issues/98.  

Votre contribution à nos articles est grandement appréciée.   

Cordialement,  
L’équipe Microsoft DOCS International
